# Path to your oh-my-zsh installation.

export ZSH=~/.oh-my-zsh

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes

ZSH_THEME="spaceship"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=(asdf docker doctl gh git golang helm kubectl)

source $ZSH/oh-my-zsh.sh

# User configuration

export EDITOR='vim'

show-path() {
    awk -v RS=: '{print}' <<< $PATH
}

alias gs='git status'
