vim.opt.backup = false -- make a backup before overwriting a file
vim.opt.clipboard = "unnamedplus" -- use clipboard register for all yank, delete, change, and put operations
-- vim.opt.colorcolumn = "80" -- comma separated list of screen columns that are highlighted
vim.opt.cursorline = false -- highlight text line containing the cursor
vim.opt.expandtab = true -- spaces instead of tabs
vim.opt.fileencoding = "utf-8" -- file content encoding, defaults to UTF-8
vim.opt.ignorecase = true -- ignore case in search patterns
vim.opt.number = true -- display line numbers
vim.opt.relativenumber = false -- display relative line numbers
vim.opt.scrolloff = 8 -- minimal number of screen lines to keep above and below the cursor, wrap needs to be false
vim.opt.shiftwidth = 2 -- indent spaces
vim.opt.showmode = false -- if in insert, replace, or visual mode put a message on the last line
vim.opt.sidescrolloff = 8 -- minimal number of screen columns to keep on the left and to the right of the cursor
vim.opt.signcolumn = "yes" -- always draw sign column
vim.opt.smartcase = true -- override the ignorecase option if the search pattern contains upper case characters
vim.opt.smartindent = true -- do smart auto-indenting
vim.opt.splitbelow = true -- horizontal splits go below current window
vim.opt.splitright = true -- vertical splits go to the right of current window
vim.opt.swapfile = false -- use a swap file for the buffer
vim.opt.tabstop = 2 -- number of spaces a <Tab> in the file counts for
vim.opt.termguicolors = true -- enables 24-bit RGB color in the TUI. Requires ISO-8613-3 compatible terminal
vim.opt.timeoutlen = 300 -- time in milliseconds to wait for a mapped sequence to complete
vim.opt.undofile = true -- save undo history to an undo file
vim.opt.updatetime = 300 -- if this many milliseconds nothing is typed the swap file be written to disk
vim.opt.wrap = false -- disable line wrapping
vim.opt.writebackup = false -- make a backup before overwriting a file
